### ISSUE TITLE
Add logos

### ISSUE THREAD

**Issue by relekang** [abakus-ntnu/grafisk-profil#2]
Add inn a `logo` folder
#### Abakus logo with black text
- [x] png
- [x] svg
#### Abakus logo with white text
- [x] png
- [x] svg
#### Square Abakus logo with only the ball
- [x] png
- [x] svg

**Comment by mathiasose** [comment]
- [ ] Pure CSS

**Comment by relekang** [comment]
@mathiasose Nice, it could at least be done for the square logo :)
